language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
install:
  - pip install Django==$DJANGO_VERSION --use-mirrors
  - python setup.py install
script: python runtests.py
